### ISSUE TITLE
Sapporo-Web doesn't retrieve executable_workflows correctly from new Sapporo-wes 1.0.1

### ISSUE THREAD

**Issue by nabito** [sapporo-wes/sapporo-web#26]
Usually when register for a new WES endpoint, the executable workflow originally will be retrieved from `/service-info`

This is the part of code that use it:
`src/store/services.ts:269:    if (serviceInfo.executable_workflows) {`

However, in wes-1.0.1 it probably should get this info from `/executable-workflows`

Is my understanding correct?

**Comment by suecharo** [comment]
@nabito 
It is correct.
The latest version of `sapporo-service` is `1.1.0`, which is `wes 1.0.1`.
However, the current latest version of sapporo-web, `1.0.13`, does not support `wes 1.0.1` yet. (We will do it within a month).
So, please use [`sappoor-service 1.0.20`](https://github.com/sapporo-wes/sapporo-service/releases/tag/1.0.20), the last version that supports `wes 1.0.0`.

**Comment by nabito** [comment]
@suecharo Thank you for the advice!

**Comment by suecharo** [comment]
@nabito 
NOT: `We will do it within a month`
I'm fixing it now, today.
