### ISSUE TITLE
Sapporo-web forms an invalid /runs request to Sapporo-wes version 1.0.1

### ISSUE THREAD

**Issue by nabito** [sapporo-wes/sapporo-web#27]
It forget to include `workflow_engine_name` attribute to make POST /runs to Sapporor-wes server.

This is because miss in version check.

In `/src/store/runs.ts` line 214:
```
      payload.service.serviceInfo.supported_wes_versions.includes(
        'sapporo-wes-1.0.0'
      )
```
should include:
```
      payload.service.serviceInfo.supported_wes_versions.includes(
        'sapporo-wes-1.0.1'
      )
```
Or even better, should use semver compare instead:
See: https://stackoverflow.com/a/30256597

**Comment by suecharo** [comment]
@nabito 
Thanks for the advice.
I'll try using `semver`.
As with issue #26, this problem is caused by that the latest version of `sapporo-web` does not yet support wes 1.0.1.

**Comment by suecharo** [comment]
@nabito 
I have released a new [`sapporo-web`](https://github.com/sapporo-wes/sapporo-web/releases/tag/1.1.0) that supports `sapporo-wes-1.0.1`.
Please try it.
