### ISSUE TITLE
After an HTTP 400 error when clicking on "Execute" the button stays disabled

### ISSUE THREAD

**Issue by kinow** [sapporo-wes/sapporo-web#30]
Hi!

I'm adding a new workflow to learn more about Sapporo. I managed to fetch the `streamflow.yml` and attach too the `hello.cwl` from this gist: https://gist.github.com/kinow/2b67219a013f1d0ea5f3432e768d16b6#file-streamflow-yml

Then, after selecting StreamFlow as Workflow Engine, the "Execute" button was enabled. Clicking on it, in the Sapporo Service logs I can see an error 400.

![image](https://user-images.githubusercontent.com/304786/159156522-2538f063-9284-492c-9d6a-604d83e970d6.png)

After that, I tried changing the UI elements to see if the Execute button would be enabled again, but looks like the only way to get it working again is by refreshing the UI? I confirmed with Vue Dev Utils that the component is really disabled.

![image](https://user-images.githubusercontent.com/304786/159156577-80c72452-38a2-4756-b9c8-d42afd0842a9.png)

**Comment by kinow** [comment]
Submitted it again after refreshing, the error returned was:

```json
{
  "msg": "The workflow engine name `streamflow` is not supported.", 
  "status_code": 400
}
```

**Comment by kinow** [comment]
Also, I think the error needs to be displayed to the user in the UI. Cannot recall if I saw an alert but dismissed it...

**Comment by kinow** [comment]
Ah, confirmed, definitely no feedback in the UI. Let me create another issue.

**Comment by suecharo** [comment]
Fixed in https://github.com/sapporo-wes/sapporo-web/releases/tag/1.2.0. Thanks.
