### ISSUE TITLE
Display HTTP errors in the UI

### ISSUE THREAD

**Issue by kinow** [sapporo-wes/sapporo-web#31]
Related to #30 .

I executed a workflow, but there was an HTTP error 400 that was not displayed in the UI. The only way to find it was by looking at the browser console, and Sapporo Service logs.

I think it would be best to display these errors to the users, so they can contact their IT departments for support, or alter their parameters.

Cheers
Bruno

**Comment by suecharo** [comment]
I'm planning to do some work on sapporo-web this week, so I'll do it on the side.

**Comment by suecharo** [comment]
Fixed in https://github.com/sapporo-wes/sapporo-web/releases/tag/1.2.0. Thanks.
