### ISSUE TITLE
Form entered values are cleared if you modify the upload workflow text

### ISSUE THREAD

**Issue by kinow** [sapporo-wes/sapporo-web#32]
Steps to reproduce:

1. Visit Sapporo Web
2. Select a WES Service
3. Click + Add to add a new Workflow
4. Select Uload
5. Type anything in the input field; it will enable other fields, such as Name, Type, Version, etc
6. Select a value for every field, e.g.
![image](https://user-images.githubusercontent.com/304786/161180987-0008072f-173c-4623-8c57-de5df4e94c4a.png)
7. Now type anything in the text area (in this case, it was `abc`, and I typed `d`, making it `abcd`
![image](https://user-images.githubusercontent.com/304786/161181123-feee5029-dee2-4654-82b4-b145b08d566a.png)

Now the Type and the Version of the Workflow Engine have been cleared and the user needs to fill those two values again. The other values are not modified.

**Comment by suecharo** [comment]
Fixed in https://github.com/sapporo-wes/sapporo-web/releases/tag/1.2.0. Thanks.
