### ISSUE TITLE
Add Workflow button stops working after pressing ESC

### ISSUE THREAD

**Issue by kinow** [sapporo-wes/sapporo-web#34]
Hi,

I've just synced `sapporo-web` with `main` to test a StreamFlow workflow. After pressing “Add”, a pop-up is shown. If I press ESC without entering anything in the form, the pop-up is gone. Now, pressing “Add” again won't show the pop-up anymore until I refresh the tab.

In the GIF below I first closed the form by clicking outside. The “Add” button still works. Then, after the pop-up is displayed again, I now dismiss it with ESC, and then the issue occurs.

Thanks!

![GIFrecord_2022-04-12_190922](https://user-images.githubusercontent.com/304786/162901854-fc388943-7e5d-4c62-be19-9795e8c87faf.gif)

**Comment by suecharo** [comment]
Fixed in https://github.com/sapporo-wes/sapporo-web/releases/tag/1.2.0. Thanks.
